FROM alpine
LABEL maintainer="connor@connortech.me"
LABEL name: "Deepface-models"
LABEL description: "Collection of deepface models to be used by deepface-server"

RUN mkdir -p /root/.deepface/weights
ADD "https://github.com/serengil/deepface_models/releases/download/v1.0/facial_expression_model_weights.h5" /root/.deepface/weights
ADD "https://github.com/serengil/deepface_models/releases/download/v1.0/age_model_weights.h5" /root/.deepface/weights
ADD "https://github.com/serengil/deepface_models/releases/download/v1.0/gender_model_weights.h5" /root/.deepface/weights
ADD "https://github.com/serengil/deepface_models/releases/download/v1.0/race_model_single_batch.h5" /root/.deepface/weights
ADD "https://github.com/serengil/deepface_models/releases/download/v1.0/arcface_weights.h5" /root/.deepface/weights
ADD "https://github.com/serengil/deepface_models/releases/download/v1.0/deepid_keras_weights.h5" /root/.deepface/weights
ADD "https://github.com/serengil/deepface_models/releases/download/v1.0/facenet_weights.h5" /root/.deepface/weights
ADD "http://dlib.net/files/dlib_face_recognition_resnet_model_v1.dat.bz2" /root/.deepface/weights
ADD "https://github.com/serengil/deepface_models/releases/download/v1.0/facenet512_weights.h5" /root/.deepface/weights
ADD "https://github.com/swghosh/DeepFace/releases/download/weights-vggface2-2d-aligned/VGGFace2_DeepFace_weights_val-0.9034.h5.zip" /root/.deepface/weights
ADD "https://github.com/serengil/deepface_models/releases/download/v1.0/openface_weights.h5" /root/.deepface/weights
ADD "https://github.com/opencv/opencv_zoo/raw/master/models/face_recognition_sface/face_recognition_sface_2021dec.onnx" /root/.deepface/weights
ADD "https://github.com/serengil/deepface_models/releases/download/v1.0/vgg_face_weights.h5" /root/.deepface/weights
